### ISSUE TITLE
Problems installing the pipeline

### ISSUE THREAD

**Issue by ArijRB** [Hamza5/Pipeline-diacritizer#5]
Thank you for your contribution, I am trying to download and install Pipeline-diacritizer is by using pip bur i get an error that no matching distribution found. Thank you in advance.

**Comment by Hamza5** [comment]
Hi, I used my code on Python 3.6 and 3.7, so I made this tool available to _Python from 3.4 to 3.7_ in order to not run into compatibility problems. Make sure that you are using **Python 3.7 at max** and not a newer version (not 3.8 or 3.9).

I know that this restriction is bad, but I don't have time to maintain this code because I am working on another project and planning to deprecate this one.

**Comment by ArijRB** [comment]
Thank you for your answer. Do you plan on sharing a trained version of the system?

**Comment by Hamza5** [comment]
You are welcome. For this project, I don't think so, because I made some terrible design mistakes that made it very slow to train and really resource-intensive. That's because I was a beginner in **Tensorflow**. Furthermore, the server that I used for training has now some problems that seem to not be solved anymore, and I don't have the training weight files and I can't do the training again on that server.

However, as I told you, I am working on a much better project, and I won't fall into the previous mistakes. In the next project, I will release a trained and optimized model that can be used directly.
